Add Indonesian Language
octokatherine/readme.so pull request #150
Opened 2021-05-27 09:26 UTC by danarn17

#149

2021-05-29 03:29 UTC, katherinepeterson commented
@danarn17 I believe someone already opened a PR for this 
#122

2021-05-29 05:26 UTC, danarn17 commented
> @danarn17 I believe someone already opened a PR for this
> #122

sorry, I just realize that after open this PR.

I will resolve the conflict. Of course, it is up to you if you would merge this or not. :)

2021-08-17 04:27 UTC, octokatherine requested changes
Can you resolve conflicts and remove the extra newline added? Thanks!

2021-08-17 04:27 UTC, octokatherine commented on components/SectionsColumn.js
> +
```suggestion
```

2021-08-17 09:39 UTC, danarn17 commented
> Can you resolve conflicts and remove the extra newline added? Thanks!

done

2021-08-18 21:06 UTC, merged